# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsgames-shop-backend
  labels:
    app: lsgames-shop-backend
  namespace: smkz-for-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsgames-shop-backend
  template:
    metadata:
      labels:
        app: lsgames-shop-backend
    spec:
      containers:
        - name: lsgames-shop-backend
          image: $secrets.REGISTRY_URL/lsgames-shop-backend:latest
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ConnectionStrings__LSGamesShop
              valueFrom:
                secretKeyRef:
                  name: lsgames-shop-secrets
                  key: database.host
            - name: Credentials__LSGamesShop__Username
              valueFrom:
                secretKeyRef:
                  name: lsgames-shop-secrets
                  key: database.username
            - name: Credentials__LSGamesShop__Password
              valueFrom:
                secretKeyRef:
                  name: lsgames-shop-secrets
                  key: database.password
            - name: Swagger__RoutePrefix
              valueFrom:
                configMapKeyRef:
                  name: lsgames-shop-configs
                  key: swagger.route.prefix
            - name: Services__SingleSignOn
              valueFrom:
                configMapKeyRef:
                  name: lsgames-shop-configs
                  key: services.singlesignon

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lsgames-shop-backend
  namespace: smkz-for-work
spec:
  type: ClusterIP
  selector:
    app: lsgames-shop-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
